# https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-python
name: oeg.feature.class tests

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['2.7', '3.6', '3.7', '3.8']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tests/requirements.txt

    - name: flake8
      run: |
        flake8 --count --show-source --statistics --max-line-length=120 oeg.feature.class
        flake8 --count --show-source --statistics --max-line-length=120 tests/test

    - name: pylint
      run: |
        python -m pylint oeg.feature.class
        python -m pylint tests/test

    - name: pytest
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      run: |
        pytest --cov=oeg.feature.class --cov-report xml --cov-report term:skip-covered --durations=5 tests
        python-codacy-coverage -r coverage.xml
